version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    expose:
      - 4000
    volumes:
      - './backend:/usr/src/app'
    depends_on:
      - 'redis'
    environment:
      - REDIS_URL=redis://redis:6379
      - HOST=0.0.0.0
      - ENV=prod
      - PORT=4000
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        # Inject backend URL into frontend's Dockerfile
        VITE_BACKEND_API_URL: https://omar2205-bit-ly-like-service-w9qrg5r2g6pj-4000.githubpreview.dev/
    ports:
      - '5000:80'
    restart: always

  redis:
    image: redislabs/redisearch
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data: